input.onGesture(Gesture.Shake, function () {
    music.play(music.stringPlayable("G F G A - F E D ", 120), music.PlaybackMode.LoopingInBackground)
    basic.showIcon(IconNames.Sad)
    basic.pause(1000)
    basic.showString("ez fajt")
    basic.clearScreen()
    basic.pause(2000)
    basic.showIcon(IconNames.Sad)
    basic.pause(1000)
    music.stopAllSounds()
    basic.pause(1000)
    basic.showIcon(IconNames.Asleep)
})
input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    music._playDefaultBackground(music.builtInPlayableMelody(Melodies.Entertainer), music.PlaybackMode.LoopingInBackground)
    basic.showIcon(IconNames.Happy)
    basic.pause(1000)
    basic.showString("köszi a simit")
    basic.pause(2000)
    music.stopAllSounds()
    basic.showIcon(IconNames.Asleep)
})
basic.showString("SZEAAA")
basic.showIcon(IconNames.Asleep)
